[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Backend service configuration
[deploy.services.backend]
startCommand = "python main.py"
healthcheckPath = "/health"

# Frontend service configuration  
[deploy.services.frontend]
startCommand = "cd web && npm run start"
healthcheckPath = "/"