[build]
builder = "nixpacks"

[deploy]
startCommand = "cd web && npm run start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.services.web-frontend]
startCommand = "cd web && npm run start"