# mobile/pubspec.yaml
name: subscription_tracker
description: "Многоплатформенный трекер подписок"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.2
  riverpod: ^2.5.1
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  flutter_dotenv: ^5.2.1
  url_launcher: ^6.3.1
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - assets/images/